#!/bin/bash
#QSUB -eo
#QSUB -lT 3600 -lM 1gb  -l mpp_p=4
export OMP_NUM_THREADS=1

### LoadLeveler on ULAM and VARGAS
## title of the run
# @ job_name = zz-make_movies
## Output listing location
# @ output = $(job_name).$(jobid)
# @ error  = $(output)
# @ job_type = serial
# @ wall_clock_limit = 72000
# @ as_limit = 2.0gb
# @ queue

#set -x

#-------------------------------------------------------------------------------
#  $Date: 2009-03-03 (Tue, 03 Mar 2009) $
#  $History: (03/2009) adapted to PERIANT configurations by C. Dufour $
#            (04/2009) adapted to the new LEGI web host $
#-------------------------------------------------------------------------------

. ./config_def
. ./function_def

nb_month=12
first_month=1

copy() {
          ssh drakkar@ige-meom-drakkar.u-ga.fr -l drakkar " if [ ! -d DRAKKAR/$CONFIG ] ; then mkdir DRAKKAR/$CONFIG ; fi "
          ssh drakkar@ige-meom-drakkar.u-ga.fr -l drakkar \
         " if [ ! -d DRAKKAR/$CONFIG/$CONFCASE ] ; then mkdir DRAKKAR/$CONFIG/$CONFCASE ; fi "
          ssh drakkar@ige-meom-drakkar.u-ga.fr -l drakkar \
         " if [ ! -d DRAKKAR/$CONFIG/$CONFCASE/${dir} ] ; then mkdir DRAKKAR/$CONFIG/$CONFCASE/${dir} ; fi "
          scp $gifmov drakkar@ige-meom-drakkar.u-ga.fr:DRAKKAR/$CONFIG/${CONFCASE}/${dir}/$gifmov ;}

mkgif() {
            ctrans -device sun -res 1024x1024 $1 > p.sun
            convert p.sun p.gif
            mv p.gif GIFS/$2
        }


cd $PLOTDIR/$CONFIG/PLOTS/$CONFCASE                             # work on ergon directly

 for dir in GLOBAL ; do # DRAKE CAMPBELL KERGUELEN SECTIONS OVT CIRCUM ICE DWBC MXL ; do
    if [ -d $dir ] ; then 
    cd $dir
    # determine the different type of plots from reference year cgms
    for  type in $( ls | grep ${CASE}.cgm  | sed -e "s/_........-${CASE}.cgm//" \
                    | sort -u ) $( ls | grep ._....-${CASE}.cgm \
                    | sed -e "s/_....-${CASE}.cgm//" | sort -u )   ; do
      if [ -f ${type}-${CASE}.catalog ] ; then 
        lastdoney=$( tail -13 ${type}-${CASE}.catalog )
        todoy=$( echo $lastdoney | awk '{ printf "%04d", $1  + 1 }' )
        todom=$first_month
        init=0
      else
        init=1
        # initialize todo to the first year of this type
        tmp=$( ls  ${type}_*.cgm | head -1 ) ; todoy=$( echo ${tmp#${type}_y} | cut -c 1-4 )
        todom=$( echo ${tmp#${type}_y${todoy}m} | cut -c 1-2 )
      fi

      last=$( ls -r ${type}_*.cgm | head -1 )
      untily=$( echo ${last#${type}_y} | cut -c 1-4 )
      untilm=$( echo ${last#${type}_y${untily}m} | cut -c 1-2 )
      echo working in $dir for  type  $type , year $todoy  to  $untily

        year=$todoy
        month=$( printf "%02d" $todom )
        if  (( $year > $untily )) ; then  echo nothing to do for $type ; fi
        if  (( $month > $untilm )) ; then  echo nothing to do for $type ; fi

        while [ $year -le  $untily  ] ; do
          echo $year
          echo $year >> ${type}-${CASE}.catalog
          while [ $month -le  $untilm  ] ; do
            month=$( printf "%02d" $month )
            echo $month
            cgm=${type}_y${year}m${month}*${CASE}.cgm  
            gif=${cgm%.cgm}.gif
            gifmov=$( echo $cgm | sed -e "s/y${year}m${month}/MONITOR/" -e 's/.cgm/.gif/'  )
            if [ -f $cgm  ] ; then
             if [ ! -f GIFS/$gif ] ; then
               mkgif $cgm $gif  # build gif file and put it in GIFS directory
             fi

             if [ $init == 1 ] ; then
               mv GIFS/$gif  $gifmov
               echo $month >> ${type}-${CASE}.catalog
               init=0
             else
               gifsicle -d100 -l0 $gifmov GIFS/$gif > tmp
               \mv tmp $gifmov
               echo $month >> ${type}-${CASE}.catalog
             fi

#            if [ $year == $refyear ] ; then init=0  ; fi
            else
             echo $cgm is not already available 
            fi
            month=$(( month +1 ))
          done
          month=$first_month  
          year=$(( year + 1 ))
        done

    # copy to the website ${toto:=none}
        if [ ${gifmov:=none} != none ] ; then
          copy
        fi
        gifmov=
    done
    cd ../
    else
        echo $dir does not exit, going my way forward
    fi   # if dir does'nt exist
done

