#!/bin/bash
CONFIG=eORCA025.L75

TGTDIR=PACIFIC    # ATLIND PACIFIC
SRCDIR=TEMPERATURE

cd $WORK/${CONFIG}

for t in S GAI AI GA GI ; do
   CASE=IMHOTEP.$t
   CONFCASE=${CONFIG}-${CASE}

   ssh monitor "mkdir -p DRAKKAR/${CONFIG}/${CONFCASE}/$TGTDIR"
   scp ${CONFCASE}-PLOT/$SRCDIR/PACIF/*mp4 monitor:DRAKKAR/${CONFIG}/${CONFCASE}/$TGTDIR/
done

