#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH --ntasks-per-node=40
#SBATCH -A cli@cpu
##SBATCH --partition=archive
#SBATCH --hint=nomultithread
#SBATCH -J JOB_trj_EGAI
#SBATCH -e zjobtrj.e%j
#SBATCH -o zjobtrj.o%j
#SBATCH --time=2:00:00
#SBATCH --exclusive

set -x 

CONFCASE=$1
n1=$2
n2=$3
nproc=480
nmember=10

CONFIG=${CONFCASE%-*}
CASE=${CONFCASE#*-}

#==========================================

CONFCASE=${CONFIG}-${CASE}
rootdir=$DDIR

OBSDIR=$DDIR/${CONFIG}/${CONFCASE}-S/OBS
SOBSDIR=$SDIR/${CONFIG}/${CONFCASE}-S/OBS

TRJDIR=$DDIR/${CONFIG}/${CONFCASE}-S/ICBTRJ
STRJDIR=$SDIR/${CONFIG}/${CONFCASE}-S/ICBTRJ

CTLDIR=$PDIR/RUN_${CONFIG}/${CONFCASE}/CTL/
DBfile=${CTLDIR}/${CONFCASE}.db

mkdir -p $OBSDIR
mkdir -p $SOBSDIR

mkdir -p $TRJDIR
mkdir -p $STRJDIR
for member in $(seq 1 $nmember) ; do
   mbr=$( printf "%03d" $member )
   STRJDIR=$SDIR/${CONFIG}/${CONFCASE}.${mbr}-S/ICBTRJ
   mkdir -p $STRJDIR
   nn=0
   for n in $(seq $n1 $n2)  ; do
     tmp=$(head -$n $DBfile | tail -1 | awk '{print $4}')
     year=${tmp:0:4}
     mont=${tmp:4:2}
     dayf=${tmp:6:2}
     echo $year

#  #  recombine OBS file in yearly fdbk format
#  cd $rootdir/${CONFCASE}-DIAOBS.$n
#  fbcomb.exe $OBSDIR/${CONFCASE}_y${year}_enact4_fdbk.$n.nc profb_fdbk_????.nc

#  #  copy  model results to STORE ( almost 2h per year ! )
#  cd $rootdir/${CONFCASE}-XIOS.$n
#  ../dcmtk_mvnc2s_bbcp

  # Iceberg trajectories:
     cd $rootdir/${CONFCASE}-ICB.$n/${mbr}
     cp $CTLDIR/icb_pp.py ./
     tmp=$( ls trajectory_icebergs*_0000.nc )
     pattern=${tmp%0000.nc}

     (  python icb_pp.py -t $pattern -n $nproc -o $TRJDIR/${CONFCASE}.${mbr}_y${year}m${mont}d${dayf}_trajectory_icebergs.$n.nc
       dd bs=100M if=$TRJDIR/${CONFCASE}.${mbr}_y${year}m${mont}d${dayf}_trajectory_icebergs.$n.nc of=$STRJDIR/${CONFCASE}.${mbr}_y${year}m${mont}d${dayf}_trajectory_icebergs.$n.nc ) &
     nn= $(( nn + 1 ))
     if [ $nn = 24 ] ; then
        wait
        nn=0
     fi

   done
   wait
done
